/* SPDX-License-Identifier: LicenseRef-SpongeOS-Proprietary
 *
 * sponge_themed — theme resolver daemon (Phase 5b).
 *
 * A long-lived, signal-driven Genode component (plain base, no Qt, no
 * libc). It is the middle hop of the one-way theme pipeline:
 *
 *   vct  --[config_request]-->  sponge_configd  --[config broadcast]-->
 *   sponge_themed  --[theme report]-->  sponge-de
 *
 * What it does:
 *   - Watches sponge_configd's broadcast "config" ROM (Attached_rom_dataspace
 *     "config" + sigh; report_rom policy
 *     `label: sponge_themed -> config | report: sponge_configd -> config`).
 *   - Reads the "theme.active" key (default "default") from that ROM.
 *   - Resolves the named theme by opening a "<name>.theme" ROM module
 *     (e.g. default.theme, light.theme), staged in the boot image.
 *   - Republishes the resolved theme CONTENT verbatim via an
 *     Expanding_reporter (node "theme", label "theme"; report_rom policy
 *     `label: sponge-de -> theme | report: sponge_themed -> theme`).
 *
 * Why content (raw INI) and not parsed values:
 *   sponge_themed is Qt-free and owns no renderer. The Qt-free
 *   ThemeLoader already lives in sponge-de (where the renderer is), so
 *   themed stays a pure name->content relay: it resolves WHICH file is
 *   active and ships its bytes, and sponge-de interprets them. This
 *   keeps interpretation in exactly one place and avoids duplicating
 *   the parser across components.
 *
 * Determinism / robustness:
 *   - The report carries the theme name as the "name" attribute and the
 *     raw theme bytes as the node's decoded text content, so a watcher
 *     (sponge-de or a probe) can assert on either.
 *   - The report is regenerated only when the resolved theme NAME
 *     changes (configd already de-duplicates its broadcast; matching
 *     that keeps unrelated config writes from needlessly republishing
 *     an identical theme and re-triggering sponge-de's re-style).
 *   - An unknown theme name (no staged "<name>.theme" ROM, or a ROM
 *     open failure) is NEVER fatal: themed keeps the previously
 *     published theme and logs a warning, so the desktop never goes
 *     blank because of a typo in `vct theme apply`.
 */

#include <base/attached_rom_dataspace.h>
#include <base/component.h>
#include <base/log.h>
#include <os/reporter.h>
#include <report_session/connection.h>
#include <rom_session/connection.h>
#include <util/reconstructible.h>
#include <util/string.h>
#include <util/xml_generator.h>
#include <util/xml_node.h>

namespace Sponge::Themed {

class Main;

namespace { }

}  /* namespace Sponge::Themed */


class Sponge::Themed::Main
{
	public:

		explicit Main(Genode::Env &env);

	private:

		Genode::Env &_env;

		/*
		 * configd's broadcast store, relayed by report_rom as the "config"
		 * ROM. Regenerated by configd on every successful set (and once at
		 * startup with the defaults), so a sigh here fires on every change.
		 */
		Genode::Attached_rom_dataspace _config_rom { _env, "config" };

		Genode::Signal_handler<Main> _config_handler {
			_env.ep(), *this, &Main::_handle_config };

		/*
		 * The resolved theme content, published as a "theme" ROM (via
		 * report_rom) for sponge-de and any probe to read.
		 */
		Genode::Expanding_reporter _theme_reporter { _env, "theme", "theme" };

		/*
		 * Constructed per resolution: opened with the label
		 * "<name>.theme" once we know the active name. A missing module
		 * surfaces as Rom_connection_failed (catchable), which is the
		 * unknown-theme path.
		 */
		Genode::Constructible<Genode::Attached_rom_dataspace> _theme_rom { };

		/*
		 * The name currently published in the "theme" report. Empty until
		 * the first theme resolves. Used to de-duplicate: an unrelated
		 * config change that leaves theme.active unchanged does not
		 * republish the same theme (and thus does not re-trigger
		 * sponge-de's re-style).
		 */
		Genode::String<64> _published_name { };

		/* ---- resolution ---- */
		void _handle_config();
		bool _read_active_theme(Genode::String<64> &out) const;
		bool _resolve_and_publish(char const *name);
		void _publish(char const *name, char const *content, Genode::size_t len);
};


/* ===================== resolution ===================== */

/*
 * Extract the "theme.active" value from configd's broadcast <config>
 * store. The store is name-sorted <key name=".." value=".."/> children
 * (sponge_configd::_generate_broadcast). Returns false if the ROM is
 * invalid or the key is absent; in that case the caller keeps the
 * previous theme (graceful degradation).
 */
bool Sponge::Themed::Main::_read_active_theme(Genode::String<64> &out) const
{
	if (!_config_rom.valid())
		return false;

	try {
		Genode::Xml_node const root = _config_rom.xml();

		bool found { false };
		root.for_each_sub_node("key", [&](Genode::Xml_node const &k) {
			if (!found &&
			    k.attribute_value("name", Genode::String<64>())
			       == Genode::String<64>("theme.active")) {
				out   = k.attribute_value("value", Genode::String<64>());
				found = true;
			}
		});
		return found;
	}
	catch (Genode::Xml_node::Invalid_syntax) {
		return false;
	}
}


/*
 * Open the "<name>.theme" ROM module and republish its content. Returns
 * true on success. On any failure (ROM unavailable or invalid), the
 * previously published theme is left untouched and a warning is logged —
 * never fatal (AGENTS.md §5.3: a typo must not blank the desktop).
 */
bool Sponge::Themed::Main::_resolve_and_publish(char const *name)
{
	Genode::String<96> const rom_label(name, ".theme");

	try {
		_theme_rom.construct(_env, rom_label.string());
		_theme_rom->update();
	}
	catch (Genode::Rom_connection::Rom_connection_failed) {
		Genode::warning("sponge_themed: theme '", name,
		                "' has no staged ", rom_label,
		                " ROM; keeping previous theme");
		return false;
	}

	if (!_theme_rom->valid()) {
		Genode::warning("sponge_themed: ", rom_label,
		                " ROM invalid; keeping previous theme");
		return false;
	}

	char const *const base = _theme_rom->local_addr<char const>();
	Genode::size_t       len = _theme_rom->size();

	/*
	 * ROM dataspaces are page-aligned and padded with NUL bytes; trailing
	 * NULs are never theme content (theme_loader.cc trims them the same
	 * way). Strip them here so the republished content is clean.
	 */
	while (len > 0 && base[len - 1] == '\0') len--;

	if (len == 0) {
		Genode::warning("sponge_themed: ", rom_label,
		                " ROM is empty; keeping previous theme");
		return false;
	}

	_publish(name, base, len);

	/* Release the ROM dataspace until the next resolution; reopening on
	 * demand keeps the component's footprint minimal and avoids holding a
	 * dataspace for a theme that may no longer be active. */
	_theme_rom.destruct();

	return true;
}


/*
 * Publish the resolved theme as <theme name="...">[raw content]</theme>.
 * The raw bytes become the XML node's decoded text content, which
 * sponge-de feeds verbatim to its ThemeLoader (it parses the same INI
 * whether it came from a default.theme ROM or from this report).
 */
void Sponge::Themed::Main::_publish(char const *name,
                                    char const *content, Genode::size_t len)
{
	_theme_reporter.generate_xml([&](Genode::Xml_generator &g) {
		g.attribute("name", name);
		g.append_sanitized(content, len);
	});

	_published_name = Genode::String<64>(name);
}


/* ===================== signal handling ===================== */

void Sponge::Themed::Main::_handle_config()
{
	_config_rom.update();

	Genode::String<64> active { };
	if (!_read_active_theme(active)) {
		/* ROM not ready / key absent: keep the previous theme. */
		return;
	}

	/* De-duplicate: only republish when the active NAME actually changes.
	 * configd's broadcast fires on every successful set (even of other
	 * keys), so without this guard an unrelated panel.position set would
	 * re-trigger sponge-de's re-style for an identical theme. */
	if (_published_name == active)
		return;

	if (!_resolve_and_publish(active.string()))
		return;

	Genode::log("sponge_themed: resolved theme '", _published_name, "'");
}


/* ===================== component wiring ===================== */

Sponge::Themed::Main::Main(Genode::Env &env) : _env(env)
{
	Genode::log("sponge_themed: ready");

	/*
	 * Resolve the startup theme immediately so sponge-de can apply it
	 * before the user issues any `vct theme apply`. configd publishes the
	 * default store in its own constructor (init starts children in
	 * config order), so the broadcast is already present when we run.
	 */
	_config_rom.update();
	{
		Genode::String<64> active { };
		if (_read_active_theme(active))
			_resolve_and_publish(active.string());
		else
			Genode::warning("sponge_themed: no theme.active in config ROM at startup");
	}

	_config_rom.sigh(_config_handler);
}


void Component::construct(Genode::Env &env)
{
	static Sponge::Themed::Main main { env };
}


/*
 * Resolution touches a ROM dataspace and regenerates the theme report on
 * the stack; keep it comfortable.
 */
Genode::size_t Component::stack_size() { return 32 * 1024 * sizeof(Genode::addr_t); }
