#
# \brief  Seoul on Genode - for automated testing
# \author Alexander Boettcher
# \date   2013-06-11
#
# This run script starts the Seoul VMM for CI testing and will download
# a guest demo VM.
#

assert {[have_spec x86]}
assert {[have_spec foc] || [have_spec sel4] || [have_spec nova] || [have_spec hw]}

if {[have_cmd_switch --autopilot]} {

	assert {![have_spec x86_32]} \
		"Autopilot mode is not supported on this platform."

	assert {![have_include power_on/qemu]} \
		"Autopilot mode is not supported on this platform."

}

#
# Download demo image
#
set uri "http://depot.genode.org/alex-ab/images"
set image "seoul-auto-serial.img"
set image_gz "seoul-auto-serial.img.gz"
set sha1sum "d8e63259c61a9d4ec6027e9a2982378236268acd"

if {![file exists bin/$image]} {
	exec mkdir -p bin
	puts "Download file $image_gz from $uri"
	exec >& /dev/null wget -c -O bin/$image_gz $uri/$image_gz
	set sha1 [exec sha1sum bin/$image_gz]
	set sha1 [regexp -inline {[0-9a-h]+} $sha1]
	if {[string compare $sha1 $sha1sum]} {
		puts "SHA1 sum of binary does not match with expected one - abort"
		rm bin/$image_gz
		exit 1
	}
	exec gunzip bin/$image_gz
}

create_boot_directory

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/event_filter \
                  [depot_user]/src/init \
                  [depot_user]/src/nitpicker \
                  [depot_user]/src/pc_usb_host \
                  [depot_user]/src/usb_hid \
                  [depot_user]/src/vfs \
                  [depot_user]/src/vfs_block \
                  [depot_user]/src/vfs_import \
                  [depot_user]/src/ps2 \
                  [depot_user]/raw/drivers_interactive-pc \
                  [depot_user]/pkg/themed_wm \
                  [depot_user]/src/report_rom \
                  [depot_user]/src/platform \
                  [depot_user]/src/acpi \
                  [depot_user]/src/pci_decode \
                  [depot_user]/src/vesa_fb \
                  [depot_user]/src/boot_fb \
                  [depot_user]/src/pc_rtc \
                  [depot_user]/src/pc_nic \
                  [depot_user]/src/nic_router \
                  [depot_user]/src/seoul/2026-04-22

proc smp_vcpus { } {

	if {![have_spec nova]} { return { } }

return {
      + vcpu
      + halifax
      + vbios
      + lapic
}
}

proc fb { } {
	if {[have_cmd_switch --autopilot]} {
		return vesa_fb
	} else {
		return boot_fb
	}
}

append config {
config | verbose: no | prio_levels: 4
+ parent-provides
  + service ROM
  + service IRQ
  + service IO_MEM
  + service IO_PORT
  + service PD
  + service RM
  + service CPU
  + service VM
  + service LOG
  + service TRACE
+ default-route
  + any-service
    + parent
    + any-child
+ default | caps: 100

+ start timer | ram: 2M
  + provides
    + service Timer

+ start platform_reports | priority: -2 | ram: 2M | caps: 200
  + binary report_rom
  + provides
  | + service Report
  | + service ROM
  + config
    + policy | label: pci_decode -> system | report: acpi -> acpi
    + policy | label: platform -> devices  | report: pci_decode -> devices
    + policy | label: usb_hid -> report    | report: usb -> devices

+ start acpi | caps: 350 | ram: 6M | priority: -1
  + route
    + service Report | + child platform_reports
    + any-service
      + parent
      + any-child

+ start pci_decode | ram: 2M | caps: 350 | priority: -1
  + route
    + service ROM | label: system | + child platform_reports
    + service Report              | + child platform_reports
    + any-service
      + parent
      + any-child

+ start platform | caps: 400 | ram: 6M | managing_system: yes | priority: -2
  + provides
  | + service Platform
  | + service Dma
  + config
  | + policy | label_prefix: ps2
  | | + device ps2
  | + policy | label_prefix: ahci
  | | + pci | class: AHCI
  | + policy | label_prefix: nvme | info: yes
  | | + pci | class: NVME
  | + policy | label_prefix: nic | info: yes
  | | + pci | class: ETHERNET
  | + policy | label_prefix: audio
  | | + pci | class: AUDIO
  | | + pci | class: HDAUDIO
  | + policy | label_prefix: fb | info: yes
  | | + pci | class: VGA
  | + policy | label_prefix: usb | info: yes
  |   + pci | class: USB
  + route
    + service ROM | label: devices
    | + child platform_reports
    + any-service
      + parent
      + any-child

+ start pc_rtc | priority: -2 | ram: 2M
  + provides
    + service Rtc

+ start ps2 | priority: -2 | ram: 3M
  + config
  + route
    + service Event
    | + child event_filter | label: ps2
    + any-service
      + parent
      + any-child

+ start event_filter | caps: 90 | priority: -2 | ram: 2M
  + provides
  | + service Event
  + route
    + service ROM | label: config
    | + parent | label: event_filter.config
    + service Event
    | + child nitpicker
    + any-service
      + parent
      + any-child

+ start usb | priority: -2 | caps: 300 | ram: 12M
  + binary pc_usb_host
  + provides
  | + service Usb
  + config
  | + report | devices: yes
  | + policy | label_prefix: usb_hid
  | | + device | class: 0x3
  | + policy | label_prefix: seoul
  |   + device
  + route
    + service Report
    | + child report_rom
    + any-service
      + parent
      + any-child

+ start usb_hid | priority: -2 | caps: 140 | ram: 11M
  + config | use_report: yes
  + route
    + service Report
    | + child report_rom
    + service Event
    | + child event_filter | label: usb
    + service ROM | label: report
    | + child report_rom
    + service Usb
    | + child usb
    + any-service
      + parent
      + any-child

+ start ram_fs | ram: 38M
  + binary vfs
  + provides
  | + service File_system
  + config
  | + vfs
  | | + ram
  | | + import
  | |   + dir abc
  | |   + dir efg
  | |   + dir runtime
  | |   | + dir nic_router
  | |   | | + inline state
  | |   | |   + empty
  | |   | + dir update
  | |   | | + inline state
  | |   | |   + empty
  | |   | + dir depot_query
  | |   | | + inline blueprint
  | |   | |   + empty
  | |   | + inline state
  | |   |   + empty
  | |   + inline state_file
  | |     + empty
  | + policy | label: seoul -> / | root: / | writeable: yes
  + route
    + any-service
      + parent

+ start vfs_block | priority: -2 | caps: 400 | ram: 300M
  + provides
  | + service Block
  + config
    + vfs
    | + ram
    | + import
    |   + rom seoul-auto-serial.img
    + default-policy | file: /seoul-auto-serial.img | block_size: 512 | writeable: yes

+ start nic | caps: 300 | priority: -3 | ram: 16M
  + binary pc_nic
  + route
    + service Uplink
    | + child nic_router
    + any-service
      + parent
      + any-child

+ start nic_router | caps: 200 | priority: -2 | ram: 10M
  + provides
  | + service Nic
  | + service Uplink
  + config | verbose_domain_state: yes
    + policy | label_prefix: seoul | domain: downlink
    + policy | label_prefix: nic | domain: uplink
    + domain uplink
    | + nat
    |       domain:    downlink
    |       tcp-ports: 16384
    |       udp-ports: 16384
    |       icmp-ids:  16384
    + domain downlink | interface: 10.0.3.1/24
      + dhcp-server
      |             ip_first:        10.0.3.55
      |             ip_last:         10.0.3.155
      |             dns_config_from: uplink
      + tcp | dst: 0.0.0.0/0
      | + permit-any | domain: uplink
      + udp | dst: 0.0.0.0/0
      | + permit-any | domain: uplink
      + icmp | dst: 0.0.0.0/0 | domain: uplink

+ start fb | priority: -2 | caps: 300 | ram: 20M
  + binary } [fb] {
  + route
  | + service Report
  | | + child report_rom
  | + service Timer
  | | + child timer
  | + service Capture
  | | + child nitpicker
  | + service Platform
  | | + any-child
  | + any-service
  |   + parent
  + config

+ start nitpicker | priority: -2 | caps: 200 | ram: 12M
  + provides
  | + service Gui
  | + service Capture
  | + service Event
  + config
  | + capture
  | + event
  | + report | focus: yes | hover: yes
  | + domain pointer | layer: 1 | content: client | label: no | origin:  pointer
  | + domain panel   | layer: 2 | content: client | label: no | focus:   none
  | + domain default | layer: 3 | content: client | label: no | focus:   click | hover:   always
  | + policy         | label_prefix: pointer | domain:       pointer
  | + default-policy | domain: default
  + route
    + service Timer  | + child timer
    + service Report | + child report_rom
    + any-service
      + parent
      + any-child

+ start pointer | priority: -2 | ram: 2M
  + provides
  | + service Report
  + config | shapes: yes | verbose: no
  + route
    + service Gui
    | + child nitpicker
    + service ROM | label: hover
    | + child report_rom
    + service ROM | label: xray
    | + child report_rom
    + any-service
      + parent

+ start report_rom | priority: -2 | ram: 2M
  + provides
  | + service Report
  | + service ROM
  + config
    + policy | label: pointer -> hover | report: nitpicker -> hover
    + policy | label: pointer -> xray | report: nitpicker -> xray
    + policy | label: usb_hid -> report | report: usb -> devices

+ start wm | caps: 1200 | priority: -2 | ram: 34M
  + binary init
  + provides
  | + service Gui
  | + service Report
  | + service ROM
  + route
    + service ROM | label: config
    | + parent | label: wm.config
    + service Report | label_last: shape
    | + child pointer
    + service Gui
    | + child nitpicker
    + any-service
      + parent
      + any-child

+ start seoul | priority: -3 | caps: 2000 | ram: 512M
  + binary seoul
  + config | cpuid_native: no | vmm_memory: 64M | ld_verbose: yes
    .
    . The performance is bad for some kernels when vmm and 1. vcpu is not on same physical CPU
    .
    + kernel foc  | vmm_vcpu_same_cpu: yes | cpuid_native: no
    + kernel sel4 | vmm_vcpu_same_cpu: yes | cpuid_native: no | map_small: yes
    + machine | verbose: no
      .
      . guest physical layout:
      .
      . low area < 0xa9000
      . [1M- 3G)
      . [4G-68G)
      .
      + mem | start: 0x0         | end: 0x9a000
      + mem | start: 0x100000    | end: 0xc0000000
      + mem | start: 0x100000000 | end: 0x1100000000
      + mio | start: 0xe0000     | size: 0x10000 | readonly: 1
      x ioio
      + nullio    | io_base:   0x80
      + pic       | io_base:   0x20   | elcr_base: 0x4d0
      + pic       | io_base:   0xa0   | irq: 2 | elcr_base: 0x4d1
      + pit       | io_base:   0x40   | irq: 0
      + scp       | io_port_a: 0x92
      |           | io_port_b: 0x61
      + kbc       | io_base:   0x60   | irq_kbd: 1 | irq_aux: 12
      + keyb      | ps2_port:  0      | host_keyboard: 0x10000
      + mouse     | ps2_port:  1      | host_mouse: 0x10001
      + rtc       | io_base:   0x70   | irq: 8
      + serial    | io_base:   0x3f8  | irq: 0x4 | host_serial: 0x4711
      + hostsink  | host_dev:  0x4712 | buffer: 80
      + vga       | io_base:   0x03c0
      + acpimodel

      + vbios_disk | boot_disknr: 0 | disk_count: 1
      + vbios_keyboard | host_keyboard: 0x10000
      + vbios_mem
      + vbios_time
      + vbios_reset

      + msi
      + ioapic
      + pcihostbridge | bus_num: 0 | bus_count: 0x10 | io_base: 0xcf8 | mem_base: 0xe0000000
      + pmtimer       | io_port: 0x8000

      + vcpu
      + halifax
      + vbios
      + lapic
} [smp_vcpus] {
      + ahci  | mem: 0xe0800000
      + drive | sigma0drive: 0 | controller: 0 | port: 0
      x rtl8029 | irq: 9 | port: 0x300
      + intel82576vf | mem_mmio: 0xe0100000 | mem_msix: 0xe0120000
  + route
    + service Timer | + child timer
    + service Block | + child vfs_block
    + service Gui                   | + child wm
    + service Rtc                   | + child pc_rtc
    + service Usb                   | + child usb
    + service File_system           | + child ram_fs
    + service Report | label: shape | + child wm
    + service Report                | + child report_rom
    + any-service
      + parent
      + any-child
-
}

install_config $config

set boot_modules { }
lappend boot_modules $image
lappend boot_modules {*}[build_artifacts]
build_boot_image $boot_modules

append qemu_args " -m 2536 "
#append qemu_args " -cpu EPYC "
append qemu_args " -accel kvm -cpu host"
append_qemu_nic_args

proc check_qemu_version {qemu_version qemu_min qemu_max} {
	set version_min_list [split $qemu_min ".-"]
	set version_min_list_len [llength $version_min_list]

	set version_max_list [split $qemu_max ".-"]
	set version_max_list_len [llength $version_max_list]

	set version_list [split $qemu_version ".-"]
	set version_list_len [llength $version_list]

	set cmp 0
	set cmp_min 0
	set cmp_max 0
	set i 0

	foreach number $version_list {
		set min 0
		set max 0
		if { $i < $version_min_list_len } { set min [lindex $version_min_list $i] }
		if { $i < $version_max_list_len } { set max [lindex $version_max_list $i] }

		set cmp     [expr {$cmp  + $number * pow(1000, $version_list_len - $i) }]
		set cmp_min [expr {$cmp_min + $min * pow(1000, $version_list_len - $i) }]
		set cmp_max [expr {$cmp_max + $max * pow(1000, $version_list_len - $i) }]

		incr i
	}

	return [expr {($cmp_min < $cmp) && ($cmp < $cmp_max)}]
}

if { [have_include power_on/qemu] } {
	if {[regexp -- {-accel kvm -cpu host} $qemu_args dummy]} {
	} else {
		# Qemu TCG SVM is broken after $qemu_good_old and until before $qemu_good_new

		catch {exec qemu-system-x86_64 --version} qemu_version
		set qemu_version [regexp -inline {version[ ][0-9]+\.[0-9]+[\.0-9]*} $qemu_version]
		set qemu_version [regexp -inline {[0-9]+\.[0-9]+[\.0-9]*} $qemu_version]

		set qemu_good_old "6.0.1"
		set qemu_good_new "100.0.0-unknown"

		# Beginning with 6.1.0 the initial NPT fault is missing and actually
		# no guest memory is mapped by our VMM. Nevertheless something
		# is executed by Qemu ???
		if {[check_qemu_version $qemu_version $qemu_good_old $qemu_good_new]} {
			puts "\nYour Qemu version '$qemu_version' is not working with AMD SVM virtualisation"
			puts "Known good Qemu versions are until $qemu_good_old and starting with $qemu_good_new\n"
			exit 1
		}

		# only AMD CPUs have Qemu TCG virtualization support
		append qemu_args " -cpu EPYC"
	}
}

if { [have_cmd_switch --autopilot] } {
	append qemu_args " -nographic "
	run_genode_until {\[init -\> seoul\] VMM: #   CPU: vendor_id} 60

	set timeout 100
	expect {
		-i [output_spawn_id] ".*Hello Genode world!" { }
		timeout { puts stderr "Seoul auto test timed out" }
	}

	grep_output {(requests resources: )|(Error)|(abort called)}

	# remove Error messages which are not fatal
	unify_output {(?n)^.*ps2] Error: failed to read from port.*$} ""

	compare_output_to {}

	puts stderr "Seoul auto test successful"

} else {
	run_genode_until forever
}
