assert {[have_spec linux]}

# check that babeltrace2 is present
set babeltrace_missing [catch {
	spawn babeltrace2 -V
	expect {
		{Babeltrace 2.*}  { }
		eof { return }
		timeout { return }
	}
}]

if {$babeltrace_missing} {
	puts "\nPlease install babeltrace2 on your host system."
	exit 1;
}

# check that python-pcapng is present
set python_pcapng_missing [catch {
	spawn -noecho sh -c "echo \"import pcapng\" | python"
	expect {
		{No module}  { return }
		{not found}  { return }
		eof { }
	}
}]

if {$python_pcapng_missing} {
	puts "\nPlease install python-pcapng on your host system."
	exit 1;
}

build { app/ping server/lx_fs }

create_boot_directory

import_from_depot \
	[depot_user]/src/[base_src] \
	[depot_user]/src/init \
	[depot_user]/src/libc \
	[depot_user]/src/nic_router \
	[depot_user]/src/report_rom \
	[depot_user]/src/vfs \
	[depot_user]/src/linux_rtc \
	[depot_user]/src/trace_recorder \
	[depot_user]/raw/trace_recorder \
	[depot_user]/src/trace_recorder_policy \
	[depot_user]/src/dynamic_rom

install_config {
config | verbose: yes
+ parent-provides
  + service ROM
  + service LOG
  + service RM
  + service CPU
  + service PD
  + service IRQ
  + service TRACE

+ default-route
  + service File_system | + child vfs
  + any-service
    + parent
    + any-child

+ default | caps: 100 | ram: 1M

+ start timer
  + provides | + service Timer

+ start linux_rtc | ld: no
  + provides |  + service Rtc

+ start lx_fs | ld: no | ram: 4M
  + provides | + service File_system
  + config
    + default-policy | root: /fs | writeable: yes

+ start nic_router
  + provides
  | + service Nic
  | + service Uplink
  + config | icmp_echo_server: yes | trace_packets: yes
    + default-policy | domain: default
    + domain default | interface: 10.0.4.1/24
      + dhcp-server
                    ip_first: 10.0.4.2
                    ip_last:  10.0.4.10

+ start ping | ram: 10M
  + config
           dst_ip:     10.0.4.1
           period_sec: 1
           count:      10
           verbose:    yes

+ start dynamic_rom
  .
  . using dynamic_rom to delay enabling of trace_recorder
  .
  + provides | + service ROM
  + config
    + rom config
      + inline | + config
      + sleep  | milliseconds: 1000
      + inline
      | + config | period_ms: 3000 | enable: yes
      |   + vfs
      |   | + fs
      |   + policy
      |   | |      label_suffix: nic_router
      |   | |      thread:       ep
      |   | |      policy:       ctf0_pcapng
      |   | + pcapng
      |   | + ctf
      |   + policy | label_suffix: ping | thread: ep | policy: ctf0
      |     + ctf
      + sleep  | milliseconds: 2000
      + inline | + config
      + sleep  | milliseconds: 10000

+ start trace_recorder | caps: 200 | ram: 16M
  + route
    + service TRACE               | + parent | label:
    + service File_system         | + child lx_fs
    + service ROM | label: config | + child dynamic_rom
    + service ROM | label: platform_info
    | .
    | . serve config ROM has platform_info merely to satisfy the ROM request
    | .
    | + parent | label: config
    + any-service
      + parent
      + any-child
-
}

exec rm -rf bin/fs
exec mkdir -p bin/fs

build_boot_image [list {*}[build_artifacts] fs]

append qemu_args " -nographic "

run_genode_until {Enabled ctf writer for init -> ping -> ep} 20
set spawn_id [output_spawn_id]
run_genode_until {.*child "ping" exited with exit value 0.*} 60 $spawn_id

#######################
# validate CTF output #
#######################

set ctf_path [exec find bin/fs -type d -name nic_router]
exec test -s $ctf_path/ep

# check generated trace by reading CTF trace as fast as possible using a dummy output
exec babeltrace2 $ctf_path --output-format=dummy


##########################
# validate PCAPNG output #
##########################

# create python script for pcapng parsing
set fd [open [run_dir]/genode/check_pcapng.py "w"]
puts $fd {
import sys
import pcapng

with open(sys.argv[1], "rb") as fp:
   scanner = pcapng.FileScanner(fp)
   for block in pcapng.FileScanner(fp):
       pass
}
close $fd

set pcap_file [exec find bin/fs -name nic_router.pcapng]
exec test -s $pcap_file

# check generated trace by python script
exec python [run_dir]/genode/check_pcapng.py $pcap_file
